version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env  # Load environment variables from .env
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/html
    command: |
      bash -c "php artisan migrate --force &&
               php artisan db:seed --force &&
               php artisan l5-swagger:generate &&
               php artisan fetch:news"

  db:
    image: mysql:8.0
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:
